# Generated by Django 4.0.6 on 2024-04-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_orderitem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='required_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='staff_id',
            field=models.ForeignKey(db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.staff'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.store'),
        ),
    ]
