# Generated by Django 4.0.6 on 2024-04-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.AutoField(db_column='brand_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='category_id',
            field=models.AutoField(db_column='category_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(db_column='order_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(db_column='product_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.AutoField(db_column='stock_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
    ]
