# Generated by Django 4.0.6 on 2024-04-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_orderitem_order_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.AutoField(db_column='order_item_id', primary_key=True, serialize=False),
        ),
    ]
