version: "3.9"

services:
  bicycle:
    image: bicycle_shop:v0.4
    container_name: dev-bicycle-${PROJECT_NAME}
    ports:
      - 8030:8030
    environment:
      - POSTGRES_NAME=zsbd
      - POSTGRES_USER=zsbd
      - POSTGRES_PASSWORD=zsbd
      - POSTGRES_HOST=dev-postgres
      - POSTGRES_PORT=5432
    depends_on:
      - db
    build:
      context: ../

  db:
    image: postgres
    hostname: dev-postgres
    container_name: dev-postgres-${PROJECT_NAME}
    environment:
      - POSTGRES_DB=zsbd
      - POSTGRES_USER=zsbd
      - POSTGRES_PASSWORD=zsbd
    ports:
      - 5432:5432

#  mailhog:
#    image: mailhog/mailhog
#    container_name: dev-mailhog
#    restart: always
#    environment:
#      "MH_UI_WEB_PATH": "mailhog"
#    ports:
#      - 1025:1025
#      - 8025:8025
#    networks:
#      - internal-network

  pgadmin:
    container_name: pgadmin4_container-${PROJECT_NAME}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

networks:
  internal-network:
    ipam:
      driver: default
      config:
        - subnet: "172.24.25.0/24"
